//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BankBaseEntities : DbContext
    {
        private static BankBaseEntities _instance;
        public BankBaseEntities()
            : base("name=BankBaseEntities")
        {
        }

        public static BankBaseEntities GetContext()
        {
            if (_instance == null)
                _instance = new BankBaseEntities();
            return _instance;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<History> Histories { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Валюты> Валюты { get; set; }
        public virtual DbSet<Вклады> Вклады { get; set; }
        public virtual DbSet<Клиенты> Клиенты { get; set; }
        public virtual DbSet<Счета> Счета { get; set; }
        public virtual DbSet<Типы_вкладов> Типы_вкладов { get; set; }
    }
}
