//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Вклады
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Вклады()
        {
            this.Счета = new HashSet<Счета>();
        }
    
        public int Код { get; set; }
        public string Наименование { get; set; }
        public Nullable<int> Срок { get; set; }
        public Nullable<int> Код_валюты { get; set; }
        public Nullable<double> Ставка { get; set; }
        public Nullable<int> Код_типа_вклада { get; set; }
    
        public virtual Валюты Валюты { get; set; }
        public virtual Типы_вкладов Типы_вкладов { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Счета> Счета { get; set; }
    }
}
