//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Счета
    {
        public int Код { get; set; }
        public Nullable<int> Код_вклада { get; set; }
        public Nullable<System.DateTime> Дата_открытия { get; set; }
        public Nullable<System.DateTime> Дата_закрытия { get; set; }
        public Nullable<decimal> Сумма { get; set; }
        public Nullable<int> Код_клиента { get; set; }
    
        public virtual Вклады Вклады { get; set; }
        public virtual Клиенты Клиенты { get; set; }
    }
}
